require 'nokogiri'
require 'vcr'
require 'pry'
require 'webmock'

RSpec.describe WebAddressScraper do

  describe '.find' do

    context 'within an anchor tag' do

      before(:each) do
        VCR.use_cassette("jana") do
          response = Net::HTTP.get_response(URI('https://www.jana.com'))
          scraper = WebAddressScraper.new
          scraper.document = Nokogiri::HTML(response.body)
          @web_addresses = scraper.find
        end
      end

      it 'finds a link within the same domain ' do
        expect(@web_addresses).to include('https://www.jana.com/contact')
      end

      it 'rejects a link outside the domain' do
        expect(@web_addresses).not_to include("https://twitter.com/Jana")
      end
    end

    context 'with links generated by javascript' do

      it 'finds a links on the page within the domain' do
        expect(@web_addresses).to include('http://app.appsflyer.com/com.tumblr?pid=tumblr_internal&c=signup_page')
      end

    end

  end

end
